### ISSUE TITLE
OpenEVSE don't work in HA error - 'utf-8' codec can't decode byte 0xff in position 160: invalid start byte

### ISSUE THREAD

**Issue by Whastie** [firstof9/openevse#183]
integration still not working with version 2.1.14

This is the error that appears in the log:

2023-03-17 00:27:09.094 WARNING (MainThread) [openevsehttp.__main__] Unable to find firmware version.
2023-03-17 00:27:49.469 ERROR (MainThread) [custom_components.openevse] Error fetching OpenEVSE (openevse) data: 'utf-8' codec can't decode byte 0xff in position 160: invalid start byte
2023-03-17 00:27:49.469 WARNING (MainThread) [openevsehttp.__main__] Unable to find firmware version.

thanks

**Comment by firstof9** [comment]
What OpenEVSE firmware version are you running?

**Comment by Whastie** [comment]
This:
![image](https://user-images.githubusercontent.com/89639919/225778058-87cfae65-781b-4141-bd01-3367ba9842cd.png)

**Comment by Whastie** [comment]
Hello,

I am attaching Ha's log, which you have requested.

thank you so much
[home-assistant.log](https://github.com/firstof9/openevse/files/11000209/home-assistant.log)

**Comment by fhteagle** [comment]
> That device UI you have is unfamiliar.

Looks to me like the GUI V2 which is sort-of-released in 4.1.7 at this point.

**Comment by firstof9** [comment]
@Whastie thanks.

What shows up if you go to http://192.168.0.39/status ?

**Comment by Whastie** [comment]
changed the firmware version to:
![image](https://user-images.githubusercontent.com/89639919/225955579-7f4a5edd-141d-4260-8963-f9bc3c2eeea1.png)


but it still doesn't work



{"mode":"STA","wifi_client_connected":1,"eth_connected":0,"net_connected":1,"ipaddress":"192.168.0.39","emoncms_connected":0,"packets_sent":0,"packets_success":0,"mqtt_connected":1,"ocpp_connected":0,"rfid_failure":0,"ohm_hour":"NotConnected","free_heap":193192,"comm_sent":2928,"comm_success":2927,"rapi_connected":1,"evse_connected":1,"amp":0,"voltage":240,"pilot":32,"wh":0,"session_energy":278.7555556,"total_energy":0,"temp":307,"temp_max":317,"temp1":307,"temp2":false,"temp3":false,"temp4":false,"state":255,"status":"disabled","flags":1280,"vehicle":1,"colour":6,"manual_override":0,"freeram":193192,"divertmode":2,"srssi":-46,"time":"2023-03-17T15:53:33Z","offset":"+0100","elapsed":9473,"wattsec":1003520,"watthour":0,"gfcicount":0,"nogndcount":1,"stuckcount":0,"solar":0,"grid_ie":0,"charge_rate":0,"divert_update":1,"divert_active":false,"shaper":0,"shaper_live_pwr":0,"shaper_cur":0,"shaper_updated":false,"service_level":2,"ota_update":0,"config_version":0,"claims_version":3,"override_version":2,"schedule_version":0,"schedule_plan_version":0,"vehicle_state_update":3508,"tesla_vehicle_count":false,"tesla_vehicle_id":false,"tesla_vehicle_name":false}

**Comment by firstof9** [comment]
Also seeing this in your log:

```
2023-03-17 00:31:29.260 ERROR (MainThread) [custom_components.openevse] Error fetching OpenEVSE (openevse) data: Cannot connect to host openevse.local:80 ssl:default [Name does not resolve]
```

You might want to adjust the host to the IP address since it seems your mDNS isn't working.
Hit the `Configure` button and adjust the host/IP field and hit `Submit`.

**Comment by Whastie** [comment]
Hello, I have tried it several times with name and number (ip) and it doesn't work. 
That's the first thing I tried before doing this question. Thank you very much for helping me, I hope we deal with the problem.
Thanks

**Comment by Whastie** [comment]
{"mode":"STA","wifi_client_connected":1,"eth_connected":0,"net_connected":1,"ipaddress":"192.168.0.39","emoncms_connected":0,"packets_sent":0,"packets_success":0,"mqtt_connected":1,"ocpp_connected":0,"rfid_failure":0,"ohm_hour":"NotConnected","free_heap":194556,"comm_sent":7739,"comm_success":7738,"rapi_connected":1,"evse_connected":1,"amp":0,"voltage":240,"pilot":32,"wh":0,"session_energy":285.6441667,"total_energy":0,"temp":302,"temp_max":317,"temp1":302,"temp2":false,"temp3":false,"temp4":false,"state":255,"status":"disabled","flags":1280,"vehicle":1,"colour":6,"manual_override":0,"freeram":194556,"divertmode":2,"srssi":-45,"time":"2023-03-17T17:21:04Z","offset":"+0100","elapsed":9686,"wattsec":1028319,"watthour":0,"gfcicount":0,"nogndcount":1,"stuckcount":0,"solar":0,"grid_ie":0,"charge_rate":0,"divert_update":1,"divert_active":false,"shaper":0,"shaper_live_pwr":0,"shaper_cur":0,"shaper_updated":false,"service_level":2,"ota_update":0,"config_version":0,"claims_version":15,"override_version":6,"schedule_version":0,"schedule_plan_version":0,"vehicle_state_update":8759,"tesla_vehicle_count":false,"tesla_vehicle_id":false,"tesla_vehicle_name":false}

**Comment by firstof9** [comment]
Ok should be working fine then, I don't know why your Home Assistant is attempting to convert it to an SSL connection.

**Comment by Whastie** [comment]
Well I do not know.
Can I verify something in the configuration of ha?
I have no problems with any other equipment.
thank you

**Comment by firstof9** [comment]
Based on your log entries alone it looks like you have some kind of networking issue going on.
Make sure you only have the integration loaded once if you only have a single EVSE charger.

**Comment by Whastie** [comment]
I have uninstalled openvese again and as you can see there is no folder in custom_components.

I have reinstalled again and the same thing is still happening.
![image](https://user-images.githubusercontent.com/89639919/225995840-a9f3d2ea-3b22-41e3-884b-746f82ac8474.png)

**Comment by firstof9** [comment]
Are you still getting the same error messages?

**Comment by Whastie** [comment]
{"mode":"STA","wifi_client_connected":1,"eth_connected":0,"net_connected":1,"ipaddress":"192.168.0.39","emoncms_connected":0,"packets_sent":0,"packets_success":0,"mqtt_connected":1,"ocpp_connected":0,"rfid_failure":0,"ohm_hour":"NotConnected","free_heap":183504,"comm_sent":13456,"comm_success":13455,"rapi_connected":1,"evse_connected":1,"amp":0,"voltage":240,"pilot":32,"wh":0,"session_energy":285.6441667,"total_energy":0,"temp":285,"temp_max":317,"temp1":285,"temp2":false,"temp3":false,"temp4":false,"state":255,"status":"disabled","flags":1280,"vehicle":1,"colour":6,"manual_override":0,"freeram":183504,"divertmode":2,"srssi":-46,"time":"2023-03-17T19:17:38Z","offset":"+0100","elapsed":9686,"wattsec":1028319,"watthour":0,"gfcicount":0,"nogndcount":1,"stuckcount":0,"solar":0,"grid_ie":0,"charge_rate":0,"divert_update":4,"divert_active":false,"shaper":0,"shaper_live_pwr":0,"shaper_cur":0,"shaper_updated":false,"service_level":2,"ota_update":0,"config_version":0,"claims_version":15,"override_version":6,"schedule_version":0,"schedule_plan_version":0,"vehicle_state_update":15753,"tesla_vehicle_count":false,"tesla_vehicle_id":false,"tesla_vehicle_name":false}

**Comment by firstof9** [comment]
I mean the error message in `home-assitant.log` is it still giving you that `0xff` message?

**Comment by Whastie** [comment]
Hello

I think it stays the same.
I've updated to the latest version you just uploaded, but I still can't start the integration.
![image](https://user-images.githubusercontent.com/89639919/226115644-6a84f5ec-d3d0-428b-b736-31bd3eae9c73.png)


[home-assistant.log](https://github.com/firstof9/openevse/files/11008911/home-assistant.log)

**Comment by firstof9** [comment]
Does your home assistant not have internet access?

**Comment by Whastie** [comment]
Hello

My HA does have internet access.

Do you have any idea what could be the problem?

thank you

**Comment by Whastie** [comment]
Hi
I think the problem comes from the openevse service, it cannot connect with Ha, if it has a secure https connection, as in my case.
By configuring the computer with this security level openevse cannot access ha.
Although http is configured in the internal network, as in external it is https, the connection method internally and externally is https , but I think that openevse has not solved the connection with this type of connection.

Do you think that this could be the problem?
In that case, I suppose that it is something that you have to try to solve, right?

thank you so much


![image](https://user-images.githubusercontent.com/89639919/226169883-bad9f06c-1e34-4f91-a842-c304ece8eb31.png)

**Comment by firstof9** [comment]
I think it has to do with the github check that looks for new firmware releases. I have a library update that should solve it.

**Comment by firstof9** [comment]
Please try the `2.1.16` release and see if you still get these error messages.
Thanks.

**Comment by Whastie** [comment]
Hi

the problem continues with version 2.1.16.

I attach two log files.
v1_ access by name openevse.local
v2 access by ip

thank you very much again.

Let's see if we find the problem.
[home-assistant_v1.log](https://github.com/firstof9/openevse/files/11014741/home-assistant_v1.log)
[home-assistant_v2.log](https://github.com/firstof9/openevse/files/11014743/home-assistant_v2.log)

**Comment by firstof9** [comment]
`Cannot connect to host http:80 ssl:default [Name does not resolve]`

It says here you're not entering a hostname nor IP address.

**Comment by Whastie** [comment]
Hi

It has to be something else, I'm putting the same ip as on the web if I can access it, but from HA I can't.

![image](https://user-images.githubusercontent.com/89639919/226421654-f5d686d1-4c60-48c9-8862-f246786c1a65.png)

**Comment by Whastie** [comment]
Hello

It's the same thing that happened to you before, I don't think anything has changed.

Thank you very much for the help.

[home-assistant.log](https://github.com/firstof9/openevse/files/11021464/home-assistant.log)

**Comment by Whastie** [comment]
Hi

This is what appears when I put this ip:  http://192.168.0.39/config


many thanks for everything.

{"firmware":"8.2.0.EU","protocol":"-","espflash":4194304,"espinfo":"ESP32r3 2 core WiFi BLE BT","buildenv":"openevse_wifi_v1","version":"4.1.7","evse_serial":"X�����FFFFFFFF","wifi_serial":"E05A1BA14DA0","mqtt_supported_protocols":["mqtt","mqtts"],"http_supported_protocols":["http"],"diode_check":true,"gfci_check":false,"ground_check":true,"relay_check":true,"vent_check":true,"temp_check":true,"service":2,"scale":220,"offset":0,"max_current_soft":32,"min_current_hard":6,"max_current_hard":32,"ssid":"MOVISTAR_5BF0","pass":"_DUMMY_PASSWORD","lang":"en","www_username":"","www_password":"","hostname":"openevse-4da0","sntp_hostname":"pool.ntp.org","time_zone":"Europe/Madrid|CET-1CEST,M3.5.0,M10.5.0/3","emoncms_server":"https://data.openevse.com/emoncms","emoncms_node":"","emoncms_apikey":"","emoncms_fingerprint":"","mqtt_server":"192.168.0.15","mqtt_port":1883,"mqtt_topic":"openevse/cargador1","mqtt_user":"David","mqtt_pass":"_DUMMY_PASSWORD","mqtt_solar":"","mqtt_grid_ie":"openevse/cargador1/power1","mqtt_vrms":"openevse/cargador1/voltage_actual","mqtt_live_pwr":"","mqtt_vehicle_soc":"","mqtt_vehicle_range":"","mqtt_vehicle_eta":"","mqtt_announce_topic":"openevse/cargador1","ocpp_server":"","ocpp_chargeBoxId":"","ocpp_idTag":"","tx_start_point":"tx_pending","ohm":"","divert_PV_ratio":1.1,"divert_attack_smoothing_factor":0.4,"divert_decay_smoothing_factor":0.05,"divert_min_charge_time":600,"current_shaper_max_pwr":0,"tesla_access_token":"","tesla_refresh_token":"","tesla_created_at":18446744073709551615,"tesla_expires_in":18446744073709551615,"tesla_vehicle_id":"","rfid_storage":"","led_brightness":128,"scheduler_start_window":600,"flags":2106890,"emoncms_enabled":false,"mqtt_enabled":true,"mqtt_reject_unauthorized":true,"mqtt_retained":true,"ohm_enabled":false,"sntp_enabled":true,"tesla_enabled":false,"divert_enabled":true,"current_shaper_enabled":false,"pause_uses_disabled":true,"mqtt_vehicle_range_miles":false,"ocpp_enabled":false,"ocpp_suspend_evse":false,"ocpp_energize_plug":false,"rfid_enabled":false,"factory_write_lock":true,"mqtt_protocol":"mqtt","charge_mode":"eco"}

**Comment by firstof9** [comment]
I'm looking into a work around for this, but a proper fix would lie in firmware.

**Comment by Whastie** [comment]
Yes, I suppose the problem is in the firmware, I'll wait until you release new firmware to try it.

If you want me to do a test, count on me to try it.

Thank you very much and I hope you can solve it soon.

all the best

**Comment by firstof9** [comment]
Please see if version `2.1.17` solves your issue.

**Comment by Whastie** [comment]
Hellooooo

It already works!!
You're the best !!

Can you tell me what was happening and what did you do?

many thanks for everything.

**Comment by firstof9** [comment]
Since your evse_fimrware was reporting something with `bytes` and throwing a `UnicodeDecodeError` I added a try/except to catch that and process the reply in another way.
